version: '3.4'

services:
  backtend_website_template:
    container_name: backtend_website_template
    build: .
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./usr/src/app/